/* * ======================================================================================
 * SCRIPT: 03_data_gen_v2.sql
 * AUTHOR: KCB Kris
 * PL: Generowanie bazy zgłoszeń Galactic Support i automatyczna wektoryzacja (FIXED)
 * EN: Generating Galactic Support ticket database and automatic vectorization (FIXED)
 * ======================================================================================
 */

SET SERVEROUTPUT ON
SET TIMING ON

-- 1. CLEANUP (Safe Drop)
-- PL: Bezpieczne usuwanie tabeli - nie zgłosi błędu, jeśli tabela nie istnieje.
-- EN: Safe drop - won't raise an error if the table doesn't exist.
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE galactic_tickets PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- ORA-00942: table or view does not exist
            RAISE;
        END IF;
END;
/

PROMPT [INFO] Old table dropped (if existed).

-- 2. CREATE TABLE
-- PL: Tabela z kolumną wektorową. Wymiar 384 jest specyficzny dla modelu all-MiniLM-L6-v2.
-- EN: Table with vector column. Dimension 384 is specific to all-MiniLM-L6-v2 model.
CREATE TABLE galactic_tickets (
    ticket_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    severity        VARCHAR2(20),
    department      VARCHAR2(50),
    description     VARCHAR2(4000),
    -- PL: Wektor 384-wymiarowy, FLOAT32
    embedding       VECTOR(384, FLOAT32)
);

PROMPT [INFO] Table GALACTIC_TICKETS created.

-- 3. DATA GENERATION PROCEDURE
CREATE OR REPLACE PROCEDURE generate_scifi_data IS
    TYPE t_array IS TABLE OF VARCHAR2(200);
    
    -- Dictionary: SECURITY
    v_sec_phrases t_array := t_array(
        'Unauthorized bio-scan detected in Sector 7.',
        'Firewall breach in the neural link interface.',
        'Suspected AI hallucination bypass attempt.',
        'Airlock override codes entered incorrectly 5 times.'
    );
    
    -- Dictionary: HARDWARE
    v_hw_phrases t_array := t_array(
        'Hyper-drive core temperature exceeds 5000 Kelvin.',
        'Hull breach micro-fracture on deck 4.',
        'Life support oxygen scrubbers are vibrating.',
        'Gravity generator fluctuates causing nausea.'
    );

    -- Dictionary: OFFICE
    v_off_phrases t_array := t_array(
        'Coffee replicator is only producing tea.',
        'Holographic projector flickers during meetings.',
        'Automatic door sensor is too sensitive.',
        'Chair adjustment motor is stuck.'
    );
    
    v_chosen_desc VARCHAR2(4000);
    v_dept        VARCHAR2(50);
    v_sev         VARCHAR2(20);
BEGIN
    -- Generujemy 50 zgłoszeń / Generating 50 tickets
    FOR i IN 1..50 LOOP
        
        CASE MOD(i, 3)
            WHEN 0 THEN
                v_dept := 'SECURITY';
                v_sev  := 'CRITICAL';
                v_chosen_desc := v_sec_phrases(TRUNC(DBMS_RANDOM.VALUE(1, v_sec_phrases.COUNT + 1)));
            WHEN 1 THEN
                v_dept := 'ENGINEERING';
                v_sev  := 'HIGH';
                v_chosen_desc := v_hw_phrases(TRUNC(DBMS_RANDOM.VALUE(1, v_hw_phrases.COUNT + 1)));
            ELSE
                v_dept := 'ADMINISTRATION';
                v_sev  := 'LOW';
                v_chosen_desc := v_off_phrases(TRUNC(DBMS_RANDOM.VALUE(1, v_off_phrases.COUNT + 1)));
        END CASE;

        -- Noise adding
        v_chosen_desc := v_chosen_desc || ' [LogID: ' || DBMS_RANDOM.STRING('X', 4) || ']';

        INSERT INTO galactic_tickets (severity, department, description)
        VALUES (v_sev, v_dept, v_chosen_desc);
        
    END LOOP;
    COMMIT;
END;
/

-- 4. EXECUTE GENERATION
PROMPT [INFO] Generating synthetic data...
EXEC generate_scifi_data;

PROMPT [INFO] Calculating Embeddings (Vectorizing) using In-Database Model...
-- PL: Użycie poprawnej funkcji VECTOR_EMBEDDING zamiast VECTOR_EMBED
-- EN: Using correct VECTOR_EMBEDDING function instead of VECTOR_EMBED

UPDATE galactic_tickets 
SET embedding = VECTOR_EMBEDDING(DOC_MODEL USING description AS DATA);

COMMIT;

PROMPT [SUCCESS] Data vectorized successfully.
-- Weryfikacja
SELECT count(*) as vectorized_rows FROM galactic_tickets WHERE embedding IS NOT NULL;
